### ISSUE TITLE
Inconsistent response formats

### ISSUE THREAD

**Issue by DemonDaddy22** [DemonDaddy22/text-encryptor-server#7]
- Response objects differ for different APIs
- Requires additional checks on UI to compensate these inconsistencies

**Comment by DemonDaddy22** [comment]
@singlarobin

In case of error, the response format would be:
`{
  status: status-code,
  data: null,
  error: {
    message: error-message,
    name: error-name,
  }
}`

In case of data, the response format would be:
`{
  status: status-code,
  data: {
    message: can be content or any info message,
    ...extra-keys
  },
  error: null
}`

**Comment by singlarobin** [comment]
Now response format is consistent. Go ahead and make changes.
